# Test this locally with:
#   $ docker run --rm -it -v $(pwd):$(pwd) --workdir $(pwd) python:3 bash
#   # pip install -r docs/requirements.txt
#   # mkdocs serve
#   # mkdocs build
#   $ ls -lah site/
site_name: helmfile
site_author: Helmfile Authors

repo_name: helmfile/helmfile/
repo_url: https://github.com/helmfile/helmfile/
edit_uri: ''

docs_dir: docs

nav:
  - Home: index.md
  - Getting Started:
    - Paths Overview: paths.md
  - Advanced Features:
    - Best Practices Guide: writing-helmfile.md
    - Advanced Features: advanced-features.md
    - Secrets: remote-secrets.md
    - Shared Configuration Across Teams: shared-configuration-across-teams.md
  - About:
    - Users: users.md
    - License: license.md
    - Contributing: contributing.md

theme:
  name: readthedocs
  features:
    - navigation.tabs
  collapse_navigation: false
  hljs_languages:
    - yaml
    - dockerfile

markdown_extensions:
  # meta, toc, table and fenced_code extensions are included by default
  - extra
  - admonition
  - smarty
  - sane_lists
  - nl2br
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
